/**
 * @name exports
 * @summary Some constants used throughout the app
 */
module.exports = {
	CLIENT: 'client',
    CLIENT_DB: 'client_db',
    KAFKA_HOST: '172.20.0.6:9092',
    KAFKA: {
        // Creación y validación
        TOPIC_CREATED_PERSON: "createdPerson",
        TOPIC_CREATED_PATIENT: "createdPatient",
        TOPIC_CREATED_PRACTITIONER: "createdPractitioner",

        STATUS_CHECK_PERSON_FROM_PRACTITIONER: "CheckPerson-Practitioner",
        STATUS_CHECK_PERSON_FROM_PATIENT: "CheckPerson-Patient",

        STATUS_CHECKED_PERSON: "CheckedPerson-Person",
        STATUS_NOT_CHECKED_PERSON: "NotCheckedPerson-Person",

        // Referencias
        TOPIC_GET_LINKS: "getLinks",
        STATUS_GET_LINKS_FROM_CAREPLAN: "GetLinks-CarePlan",
        STATUS_GET_LINKS_SUCCESS: "SuccessLinks-Person",
        STATUS_GET_LINKS_ERROR: "ErrorLinks-Person",
    },
    DEFAULT_OPTIONS: {
		host: "127.0.0.1",
		port: "3001",
		headers: {
			"Content-Type": "application/fhir+json",
			"Cache-Control": "no-cache"
		}
    },
    VALIDABLE_RESOURCES: [
        'ActivityDefinition',
        'CarePlan',
        'CareTeam',
        'Condition',
        'Device',
        'Patient',
        'Person',
        'Practitioner',
        'PlanDefinition'
    ],
	COLLECTION: {
        ACCOUNT: 'Account',
        ACTIVITYDEFINITION: 'ActivityDefinition',
        ADVERSEEVENT: 'AdverseEvent',
        ALLERGYINTOLERANCE: 'AllergyIntolerance',
        APPOINTMENT: 'Appointment',
        APPOINTMENTRESPONSE: 'AppointmentResponse',
        AUDITEVENT: 'AuditEvent',
        BASIC: 'Basic',
        BINARY: 'Binary',
        BODYSITE: 'BodySite',
        BUNDLE: 'Bundle',
        CAPABILITYSTATEMENT: 'CapabilityStatement',
        CAREPLAN: 'CarePlan',
        CARETEAM: 'CareTeam',
        CHARGEITEM: 'ChargeItem',
        CLAIM: 'Claim',
        CLAIMRESPONSE: 'ClaimResponse',
        CLINICALIMPRESSION: 'ClinicalImpression',
        CODESYSTEM: 'CodeSystem',
        COMMUNICATION: 'Communication',
        COMMUNICATIONREQUEST: 'CommunicationRequest',
        COMPARTMENTDEFINITION: 'CompartmentDefinition',
        COMPOSITION: 'Composition',
        CONCEPTMAP: 'ConceptMap',
        CONDITION: 'Condition',
        CONSENT: 'Consent',
        CONTRACT: 'Contract',
        COVERAGE: 'Coverage',
        DATAELEMENT: 'DataElement',
        DETECTEDISSUE: 'DetectedIssue',
        DEVICE: 'Device',
        DEVICECOMPONENT: 'DeviceComponent',
        DEVICEMETRIC: 'DeviceMetric',
        DEVICEREQUEST: 'DeviceRequest',
        DEVICEUSESTATEMENT: 'DeviceUseStatement',
        DIAGNOSTICREPORT: 'DiagnosticReport',
        DOCUMENTMANIFEST: 'DocumentManifest',
        DOCUMENTREFERENCE: 'DocumentReference',
        ELIGIBILITYREQUEST: 'EligibilityRequest',
        ELIGIBILITYRESPONSE: 'EligibilityResponse',
        ENCOUNTER: 'Encounter',
        ENDPOINT: 'Endpoint',
        ENROLLMENTREQUEST: 'EnrollmentRequest',
        ENROLLMENTRESPONSE: 'EnrollmentResponse',
        EPISODEOFCARE: 'EpisodeOfCare',
        EXPANSIONPROFILE: 'ExpansionProfile',
        EXPLANATIONOFBENEFIT: 'ExplanationOfBenefit',
        FAMILYMEMBERHISTORY: 'FamilyMemberHistory',
        FLAG: 'Flag',
        GOAL: 'Goal',
        GRAPHDEFINITION: 'GraphDefinition',
        GROUP: 'Group',
        GUIDANCERESPONSE: 'GuidanceResponse',
        HEALTHCARESERVICE: 'HealthcareService',
        IMAGINGMANIFEST: 'ImagingManifest',
        IMAGINGSTUDY: 'ImagingStudy',
        IMMUNIZATION: 'Immunization',
        IMMUNIZATIONRECOMMENDATION: 'ImmunizationRecommendation',
        IMPLEMENTATIONGUIDE: 'ImplementationGuide',
        LIBRARY: 'Library',
        LINKAGE: 'Linkage',
        LIST: 'List',
        LOCATION: 'Location',
        MEASURE: 'Measure',
        MEASUREREPORT: 'MeasureReport',
        MEDIA: 'Media',
        MEDICATION: 'Medication',
        MEDICATIONADMINISTRATION: 'MedicationAdministration',
        MEDICATIONDISPENSE: 'MedicationDispense',
        MEDICATIONREQUEST: 'MedicationRequest',
        MEDICATIONSTATEMENT: 'MedicationStatement',
        MESSAGEDEFINITION: 'MessageDefinition',
        MESSAGEHEADER: 'MessageHeader',
        NAMINGSYSTEM: 'NamingSystem',
        NUTRITIONORDER: 'NutritionOrder',
        OBSERVATION: 'Observation',
        OPERATIONDEFINITION: 'OperationDefinition',
        ORGANIZATION: 'Organization',
        PATIENT: 'Patient',
        PAYMENTNOTICE: 'PaymentNotice',
        PAYMENTRECONCILIATION: 'PaymentReconciliation',
        PERSON: 'Person',
        PLANDEFINITION: 'PlanDefinition',
        PRACTITIONER: 'Practitioner',
        PRACTITIONERROLE: 'PractitionerRole',
        PROCEDURE: 'Procedure',
        PROCEDUREREQUEST: 'ProcedureRequest',
        PROCESSREQUEST: 'ProcessRequest',
        PROCESSRESPONSE: 'ProcessResponse',
        PROVENANCE: 'Provenance',
        QUESTIONNAIRE: 'Questionnaire',
        QUESTIONNAIRERESPONSE: 'QuestionnaireResponse',
        REFERRALREQUEST: 'ReferralRequest',
        RELATEDPERSON: 'RelatedPerson',
        REQUESTGROUP: 'RequestGroup',
        RESEARCHSTUDY: 'ResearchStudy',
        RESEARCHSUBJECT: 'ResearchSubject',
        RISKASSESSMENT: 'RiskAssessment',
        SCHEDULE: 'Schedule',
        SEARCHPARAMETER: 'SearchParameter',
        SEQUENCE: 'Sequence',
        SERVICEDEFINITION: 'ServiceDefinition',
        SLOT: 'Slot',
        SPECIMEN: 'Specimen',
        STRUCTUREDEFINITION: 'StructureDefinition',
        STRUCTUREMAP: 'StructureMap',
        SUBSCRIPTION: 'Subscription',
        SUBSTANCE: 'Substance',
        SUPPLYDELIVERY: 'SupplyDelivery',
        SUPPLYREQUEST: 'SupplyRequest',
        TASK: 'Task',
        TESTREPORT: 'TestReport',
        TESTSCRIPT: 'TestScript',
        VALUESET: 'ValueSet',
        VISIONPRESCRIPTION: 'VisionPrescription',
		CLIENT: 'Client'
	}
};
