version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "
      createdCarePlan:1:1,
      createdCareTeam:1:1,
      createdCondition:1:1,
      createdDevice:1:1,
      createdPatient:1:1,
      createdPerson:1:1,
      createdPlanDefinition:1:1,
      createdPractitioner:1:1,
      createdActivityDefinition:1:1,
      createdObservation:1:1,
      getLinks:1:1,
      getCareTeams:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
